### ISSUE TITLE
Ios cuts off the last few pages of a paragraph after changing the font size

### ISSUE THREAD

**Issue by peeter-tomberg** [futurepress/epub.js#330]
We're adding a class to the iframe's body element to define if the user has the default size (no extra class), medium size (opus-font-size-medium) or large (opus-font-size-large). 

After adding the class, we trigger a reformat:

```javascript
reader.renderer.reformat();
```

Any idea what we might be doing wrong? Happens with every book, the end of the paragraphs pages gets cut off (when going from paragraph b back to paragraph a)

```css
.opus-font-size-medium,
.opus-font-size-medium * {
    font-size: 18px !important;
}
.opus-font-size-medium H6 {
    font-size: 18px !important;
}
.opus-font-size-medium H5 {
    font-size: 22px !important;
}
.opus-font-size-medium H4 {
    font-size: 28px !important;
}
.opus-font-size-medium H3 {
    font-size: 36px !important;
}
.opus-font-size-medium H2 {
    font-size: 42px !important;
}
.opus-font-size-medium H1 {
    font-size: 54px !important;
}

.opus-font-size-large,
.opus-font-size-large * {
    font-size: 24px !important;
}
.opus-font-size-large H6 {
    font-size: 24px !important;
}
.opus-font-size-large H5 {
    font-size: 30px !important;
}
.opus-font-size-large H4 {
    font-size: 36px !important;
}
.opus-font-size-large H3 {
    font-size: 42px !important;
}
.opus-font-size-large H2 {
    font-size: 50px !important;
}
.opus-font-size-large H1 {
    font-size: 60px !important;
}
```
