### ISSUE TITLE
Problem with epub.js on mobile - Text is walking

### ISSUE THREAD

**Issue by prsolucoes** [futurepress/epub.js#709]
Hi,

I think we have a problem with epub.js on mobile - Text is walking to right.

I made a video:
https://www.dropbox.com/s/3w7yz0gte93nn7r/bug-epubjs.mov?dl=1

I made a sample:
https://github.com/prsolucoes/epubreader

This project is part of my open-source library that im finishing to after share on github. It will work on Android and iOS. Im only need fix this problem now.

The html file with the code is here (css/main.css is the main css file):
https://github.com/prsolucoes/epubreader/tree/master/www

**Comment by jontey** [comment]
I think the same issue has been posted here #364

**Comment by Thom3K** [comment]
Hi Jontey, I think you're on the right track. 
I had issues like this, I solved it with css parameters
My iframe had 1 pixel more than the div containing the iframe

**Comment by prsolucoes** [comment]
Any solution from latest version of epubjs?

**Comment by otorcatf** [comment]
The only way I could fixed this issue was set the width and height with a fixed value in the css and passing the same fixed dimensions to the renderer

```javascript
book = ePub('books/moby-dick/', { width: 256, height: 432 });
```
```css
/* For iPhone portrait layouts only */
  @media only screen and (max-device-width: 480px) and (orientation: portrait) {    
    #book iframe {
       width: 256px;
       height: 432px;
    }
  }
```
Now I need to work in a more responsive solution.
